name: Dependabot auto merge

on:
  pull_request_target

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          target: major
          github-token: ${{ secrets.GITHUB_TOKEN }}
